---
- hosts: all

  vars:
    kind_version: v0.7.0

  collections:
    - community.kubernetes

  roles:
    - name: geerlingguy.git
      become: true

    - name: community_test

  tasks:
    - name: Create a kind cluster.
      include_tasks: tasks/prepare-kind.yml

    - name: Test the k8s_info module from the collection.
      k8s_info:
        kind: Pod
        label_selectors:
          - component=kube-apiserver
      register: pod_list
      delegate_to: localhost

    - name: Test the k8s_exec module from the collection.
      k8s_exec:
        namespace: kube-system
        pod: "{{ pod_list.resources[0].metadata.name }}"
        command: date
      register: exec_output
      changed_when: false
      delegate_to: localhost

    - name: Dump the date.
      debug: var=exec_output.stdout

    - name: Run the same tasks as above, but in a standalone role.
      include_role:
        name: replay

# post_tasks:
#   - name: Delete the kind cluster.
#     include_tasks: tasks/delete-kind.yml
