---
name: CI
'on':
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:

  ansible-legacy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1

      - name: Set up Python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install ansible and other dependencies.
        run: pip install ansible ansible-lint yamllint docker molecule openshift

      - name: Run molecule default test scenario.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1

      - name: Set up Python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Ansible distribution.
        run: pip install --pre ansible>=2.10

      - name: Install other dependencies.
        run: pip install ansible-lint yamllint docker molecule openshift

      - name: Run molecule default test scenario.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  ansible-base:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1

      - name: Set up Python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Ansible base.
        run: pip install --pre ansible-base>=2.10

      - name: Install other dependencies.
        run: pip install ansible-lint yamllint docker molecule openshift

      # Allow this to fail, but have the output available for debugging.
      - name: Run molecule default test scenario.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        continue-on-error: true

  ansible-base-devel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1

      - name: Set up Python.
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Ansible base.
        run: pip install git+https://github.com/ansible/ansible

      - name: Install other dependencies.
        run: pip install ansible-lint yamllint docker molecule openshift

      # Allow this to fail, but have the output available for debugging.
      - name: Run molecule default test scenario.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        continue-on-error: true
